apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-crawler-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: my-crawler-secret
  data:
    {{- range .Values.secrets }}
    - secretKey: {{ .key }}
      remoteRef:
        key: {{ .name }}
    {{- end }}