apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: crawler-healthcheck
  namespace: nebulazone-crawler
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /actuator/health
  targetRef:
    group: ""
    kind: Service
    name: crawler-svc
