helm:
  parameters:
  - name: image.repository
    value: shlee054/nebulazone-app
    forcestring: true
  - name: image.tag
    value: main@sha256:ba2d3bf58f8ad4d556759be095a1a68ba180de12041ebe8863d0d1efd30b8e75
    forcestring: true
