helm:
  parameters:
  - name: image.repository
    value: shlee054/nebulazone-app
    forcestring: true
  - name: image.tag
    value: main@sha256:41100d59c45110a0f2a2ef348c3849179d39395f0425bdc0420c046bfa720950
    forcestring: true
