helm:
  parameters:
  - name: image.repository
    value: shlee054/nebulazone-app
    forcestring: true
  - name: image.tag
    value: main@sha256:d87795abcd8fc85aeb8cd2f13c52b54458c1b9bfb3e7633c5601d8009b325fb6
    forcestring: true
