gcp:
  projectId: wide-bastion-462810-h0

replicaCount: 3

image:
  repository: shlee054/nebulazone-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

secrets:
  - name: mysql-url
    key: SPRING_DATASOURCE_URL
  - name: mysql-username
    key: SPRING_DATASOURCE_USERNAME
  - name: mysql-password
    key: SPRING_DATASOURCE_PASSWORD
  - name: redis-host
    key: SPRING_DATA_REDIS_HOST
  - name: elasticsearch-uris
    key: ES_URI
  - name: jwt-secret-key
    key: JWT_SECRET_KEY
  - name: redis-password
    key: SPRING_DATA_REDIS_PASSWORD
  - name: aws-access-key
    key: AWS_ACCESS_KEY
  - name: aws-s3-bucket
    key: AWS_S3_BUCKET
  - name: aws-secret-key
    key: AWS_SECRET_KEY
  - name: kakao-api-key
    key: KAKAO_API_KEY
  - name: naver-api-key
    key: NAVER_API_KEY
  - name: naver-api-secret-key
    key: NAVER_API_SECRET_KEY
  - name: toss-secret-key
    key: TOSS_SECRET_KEY


logstash:
  hosts: ["34.47.74.190:5044"]
