gcp:
  projectId: wide-bastion-462810-h0

replicaCount: 3

image:
  repository: dungbik/nebulazone-app
  tag: "0.0.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 2000m
    memory: 4Gi

secrets:
  - name: mysql-url
    key: SPRING_DATASOURCE_URL
  - name: mysql-username
    key: SPRING_DATASOURCE_USERNAME
  - name: mysql-password
    key: SPRING_DATASOURCE_PASSWORD
  - name: redis-host
    key: SPRING_DATA_REDIS_HOST
  - name: elasticsearch-uris
    key: ES_URI
  - name: jwt-secret-key
    key: JWT_SECRET_KEY
  - name: redis-password
    key: SPRING_DATA_REDIS_PASSWORD

logstash:
  hosts: ["10.178.0.14:5044"]
