apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- range .Values.secrets }}
            - name: {{ .key }}
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: {{ .key }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 10
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.18.1
          args: [
            "-c", "/etc/filebeat.yml",
            "-e"
          ]
          env:
            - name: FILEBEAT_SERVICE
              value: app-filebeat
          volumeMounts:
            - name: app-logs
              mountPath: /logs
            - name: filebeat-config.yaml
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: app-logs
          hostPath:
            path: /var/log/app
            type: DirectoryOrCreate
        - name: filebeat-config.yaml
          configMap:
            name: filebeat-config