apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: my-app-secret
  data:
    {{- range .Values.secrets }}
    - secretKey: {{ .key }}
      remoteRef:
        key: projects/{{ $.Values.gcp.projectId }}/secrets/{{ .name }}/versions/latest
    {{- end }}