apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: app-healthcheck
  namespace: nebulazone-app
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 9091
        requestPath: /actuator/health
  targetRef:
    group: ""
    kind: Service
    name: app-svc
