apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: app
      port: {{ .Values.service.port }}
      targetPort: 8080
    - name: http-actuator-metrics
      port: 9091
      targetPort: 9091
  selector:
    app: {{ .Chart.Name }}
