apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-app-service-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: my-app
  endpoints:
    - port: http-actuator-metrics
      path: /actuator/prometheus
      interval: 5s
  namespaceSelector:
    matchNames:
      - nebulazone-app
